### ISSUE TITLE
TN: Backfill Actions

### ISSUE THREAD

**Issue by inertia186** [steemit/gigantor#9]
There are new features in `tinman` that allow it to build a more robust actions list.  Before generating `txgen.actions`, it needs to create a backfill.  I'm recommending a backfill of 864,000 blocks to start out.  This will get actions from 1 month ago.

```bash
tinman gatling --from_blocks_ago 864000 --to_blocks_ago 0
```

Note, `--from_blocks_ago` is a new argument for `gatling` so we don't have to calculate the block number in `bash`.

**AC**

- [x] define a backfill `gatling.conf`, as recommended by https://github.com/steemit/tinman/issues/143#issuecomment-429208721 that only enables operations that lead to interesting virtual ops (e.g.: not `comment_operation` because payouts are 1 hour on testnet), and use `prefixsub` (https://github.com/steemit/tinman/pull/160).
- [x] add new `snapshotgen-backfill.sh` with `gatling` phase to create backfill + logging messages
- [x] `Dockerfile` updated to include `libyajl-dev`

**Comment by relativityboy** [comment]
Backfill actions should be `.separate` from account `.actions`

**Comment by relativityboy** [comment]
> add new snapshotgen-backfill.sh with gatling phase to create backfill + logging messages

So we pipe gatling into txgen?

**Comment by inertia186** [comment]
Correct.  So we'll end up with two `txgen.actions`.  One with a backfill, one without.
